name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    defaults:
      run:
        # Required for miniconda (https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell)
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda with Python 3.9
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9
        auto-update-conda: true
        activate-environment: test-env
        channels: conda-forge
        channel-priority: strict
        use-only-tar-bz2: true
    - name: Cache conda packages
      id: cache-conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if conda packages are changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}
    - name: Cache pip packages
      id: cache-pip
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache even if requirements.txt didn't
        # change
        CACHE_NUMBER: 0
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('requirements.txt') }}
    - name: Install PyGMO
      run: conda install --yes --channel conda-forge pygmo=2.18.0
      if: steps.cache-conda.outputs.cache-hit != 'true'
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pytest
      working-directory: ./src
      run: |
        python -m pytest ../tests
